controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  legged_rl_controller:
    type: legged/LeggedRLController
  student_policy_controller:
    type: legged/StudentPolicyController